/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaToNative */

#ifndef _Included_JavaToNative
#define _Included_JavaToNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaToNative
 * Method:    goNative
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_JavaToNative_goNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     JavaToNative
 * Method:    goThere
 * Signature: (LCallback;)V
 */
JNIEXPORT void JNICALL Java_JavaToNative_goThere
  (JNIEnv *, jclass, jobject);

/*
 * Class:     AllocationTest
 * Method:    objectsAllocationTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AllocationTest_objectsAllocationTest
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
